import '../globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { AppProvider } from '@/app/context/AppContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'XTP - ADMIN',
    description: 'Generated by create next app',
    icons: {
        icon: '/public/icon.png',
    },
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <AppProvider>
                <body className={inter.className}>{children}</body>
            </AppProvider>
        </html>
    );
}
